Portfolio Nav-Bar and Headline Branch
sntgopl/Porfolio pull request #1
Opened 2022-06-30 19:43 UTC by sntgopl

Hello. So i worked in a secondary main branch and created new branches and merged them all to secondary to, at the end, create pull request to merge to main branch. I'll list the steps.

-Set up linters with npm command and ingored them with .gitignore.
-Completed ReadMe file information.
-Created HTML file basic structure and body skeleton. (nav-bar and headline)
-Added CSS file to correct html structure to requested template. (Figma template 2).
-Added Logo with HTML and CSS (top left).
-Added hamburger menu icon (top right)
-Created branch for headline and set up CSS Flex structure
-Added h1 head and import Google Fonts
-Added h2 head and CSS specs.
-Added last <p> comment for headline, corrected CSS structure.
-Commented out media query.

2022-06-30 19:50 UTC, Kandy-Peter reviewed
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @sntgopl 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has some issues needed to be fixed before reviewing it:
- [x] Kindly, make sure that you set up your linters correctly and that there is no linter error. In your case, I can't see the '.github' folder. You may forget to add it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏
---
_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-07-01 03:36 UTC, Ismailco requested changes
### Hi @sntgopl,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 03:36 UTC, Ismailco commented on index.html
> +        </nav>
- [ ] This section should be wrapped in a `header` tag, kindly implement this it's a requirement

2022-07-01 03:36 UTC, Ismailco commented on index.html
> +        </header>
- [ ] This section should be using the `section` tag instead of `header` kindly fix this so it has the right tag

2022-07-01 03:36 UTC, Ismailco commented on index.html
> +            <img class="background" src="images/Illustration-header.png" alt="">
- [ ] kindly consider fixing your background so the white space in the right is removed, 

![Screenshot_20220701_043009](https://user-images.githubusercontent.com/25227022/176818448-b28fa428-f6fa-453e-84eb-007c31afe963.png)

2022-07-01 15:11 UTC, Kandy-Peter approved these changes
Hi @sntgopl,

### APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

##  Optional suggestion
 
# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 15:19 UTC, merged